enum ErrorType {
  /**
   * GQL
   */
  GQL_SUBSCRIPTION_PING = 'GQL_SUBSCRIPTION_PING',
  GQL_SUBSCRIPTION_VPN = 'GQL_SUBSCRIPTION_VPN',

  /**
   * LocalStorage
   */
  LOCAL_STORAGE_UNABLE_TO_GET_STORAGE = 'LOCAL_STORAGE_UNABLE_TO_GET_STORAGE',
  LOCAL_STORAGE_UNABLE_TO_FIND_KEY = 'LOCAL_STORAGE_UNABLE_TO_FIND_KEY',
  LOCAL_STORAGE_UNABLE_TO_READ = 'LOCAL_STORAGE_UNABLE_TO_READ',
  LOCAL_STORAGE_UNABLE_TO_WRITE = 'LOCAL_STORAGE_UNABLE_TO_WRITE',
}

export { ErrorType }
