enum ErrorType {
  GQL_QUERY_PING = 'GQL_QUERY_PING',

  /**
   * LocalStorage
   */
  LOCAL_STORAGE_UNABLE_TO_GET_STORAGE = 'LOCAL_STORAGE_UNABLE_TO_GET_STORAGE',
  LOCAL_STORAGE_UNABLE_TO_FIND_KEY = 'LOCAL_STORAGE_UNABLE_TO_FIND_KEY',
  LOCAL_STORAGE_UNABLE_TO_READ = 'LOCAL_STORAGE_UNABLE_TO_READ',
  LOCAL_STORAGE_UNABLE_TO_WRITE = 'LOCAL_STORAGE_UNABLE_TO_WRITE',
}

export { ErrorType }
