language: typescript
schema: https://api.freemiumpn.com/graphql
overwrite: true
documents: "**/*.gql"
generates:
  src/generated/graphql/schema.graphql.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
    config:
      withHOC: false
      withComponent: false
      withHooks: true
      reactApolloVersion: 3
  src/generated/graphql/operations.graphql.d.ts:
    - "typescript-graphql-files-modules"
